42ity/fty-srr

include/fty-srr.h, src/fty_srr_manager.cc, src/fty_srr_worker.cc, src/fty_srr_worker.h
=> Refactoring to be compliant with the latest fty-common-dto

src/fty_srr_manager.cc
=> Using switch case with enum

include/fty-srr.h, src/fty_srr_worker.cc
=> Adding version in return

ci_build.sh, ci_dependencies.sh, configure.ac, license.xml, src/Makemodule.am
=> Update gsl, zproject

src/fty-srr.service.in
=> Fixing cyclic dependencies

src/fty_srr_worker.cc
=> Trace responses from srr agents

src/fty-srr.cfg.in
=> Increase timeout

src/fty-srr.cc
=> Increase default timeout

src/fty_srr_worker.cc
=> Removing temporarily connectors from SRR

src/fty_srr_manager.cc, src/fty_srr_manager.h
=> Temporary fix for srr hanging request

server/CMakeLists.txt, server/fty-srr-reboot.sh, server/src/helpers/utils.cc, server/sudoers/fty_20_srr
=> Add script to reboot after restore

server/src/fty_srr_worker.cc
=> Add 6 seconds delay between each feature restore

server/src/fty-srr-cmd.cc
=> Add force option to restore

server/include/fty-srr.h, server/src/fty_srr_groups.cc, server/src/fty_srr_worker.cc, server/src/locale_en_US.json
=> Add support for automatic group SRR

server/src/fty_srr_worker.cc
Signed-off-by: Hlib Yarovyi <yarovii.w@gmail.com>
=> Optimized code. Fix throw exception

server/fty-srr.cfg, server/include/fty_srr_groups.h, server/src/dto/request.cc, server/src/fty-srr-cmd.cc, server/src/fty_srr_groups.cc, server/src/fty_srr_manager.cc, server/src/fty_srr_worker.cc
- add `required in` field for each feature
- remove asset groups from 1.0 and 2.0 required features
=> Update SRR version to 2.1

server/src/fty_srr_groups.cc
This reverts commit 374449c76785ac8ac53827507972c47487b1ae6a.
=> Revert "disabled USMv2 for now"

server/src/fty_srr_worker.cc
=> Fix creation of rollback payload and reset request

server/src/fty-srr.cc
Signed-off-by: Arnaud Quette <ArnaudQuette@eaton.com>
=> Fix use of obsolete header

server/include/fty-srr.h, server/src/fty_srr_groups.cc, server/src/locale_en_US.json
=> Add virtualization settings feature and group

server/CMakeLists.txt, server/src/fty_srr_worker.cc, server/src/helpers/passPhrase.cpp, server/src/helpers/passPhrase.h
Signed-off-by: Hlib Yarovyi <HlibYarovyi@eaton.com>
=> Add translation message

packaging/debian/control, server/CMakeLists.txt
=> Remove dep from etn-licensing-lib
